import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Thumbnail from '../components/ProductThumbnail/Thumbnail';
import Header from '../components/Header/Header';
import AddToCart from '../components/AddToCart/AddToCart';
import { useEffect, useState } from 'react';
import Modal from '../components/Modal/Modal';
import { SliderData } from '../assets/SliderData';
import SliderPhone from '../components/SliderPhone/SliderPhone';

const Home = () => {
  const [counter, setCounter] = useState<Number>(0);
  const [totalCart, setTotalCart] = useState<Number>(0);
  const [showModal, setShowModal] = useState<Boolean>(false);

  useEffect(() => {
    const storage = localStorage.getItem('total');
    const total = storage ? parseInt(storage) : 0;
    setTotalCart(total);
    setCounter(total);
  }, []);

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Challenge E-commerce</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header
          totalCart={totalCart}
          setTotalCart={setTotalCart}
          setCounter={setCounter}
        />

        <main className={styles.main}>
          <Thumbnail setShowModal={setShowModal} />
          <SliderPhone />
          <div className={styles.content}>
            <p className={styles.span}>SNEAKER COMPANY</p>
            <h1 className={styles.titleContent}>
              Fall Limited Edition Sneakers
            </h1>
            <p className={styles.text}>
              These low-profile sneakers are your perfect casual wear companion.
              Featuring a durable rubber outher sole, they will withstand
              everything the weather can offer.
            </p>
            <div className={styles.price}>
              <div className={styles.subPrice}>
                <h2>$125.00</h2>
                <div className={styles.discount}>
                  <h4>50%</h4>
                </div>
              </div>
              <h4>$250.00</h4>
            </div>

            <AddToCart
              counter={counter}
              setCounter={setCounter}
              setTotalCart={setTotalCart}
            />
          </div>
        </main>
      </div>
      <Modal
        showModal={showModal}
        setShowModal={setShowModal}
        slides={SliderData}
      />
    </>
  );
};

export default Home;
